# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auction_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Product'),
        ),
    ]
