# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 13:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('categories-menu-items', 'Categories Menu Items')], max_length=255, unique=True)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'verbose_name_plural': 'SiteSettings',
            },
        ),
    ]
