# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-06 01:49
from __future__ import unicode_literals

from django.db import migrations
from site_settings.types import CATEGORIES_MENU_ITEMS


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    SiteSettings = apps.get_model("site_settings", "SiteSettings")
    SiteSettings.objects.create(
      type=CATEGORIES_MENU_ITEMS,
      value=["women", "men", "kids", "jewellery", "home decor", "accessories", "staff picks"]
    )


def reverse_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    SiteSettings = apps.get_model("site_settings", "SiteSettings")
    SiteSettings.objects.filter(type=CATEGORIES_MENU_ITEMS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
