# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-31 16:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(7), django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
